[package]
name = "pavao"
version = "0.1.0"
authors = ["Christian Visintin <christian.visintin1997@gmail.com>"]
edition = "2021"
categories = ["network-programming"]
description = "Rust client library for SMB 2/3 based on libsmbclient."
documentation = "https://docs.rs/pavao"
homepage = "https://github.com/veeso/pavao"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["smb", "samba", "network-protocol", "smb2", "smb3"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/veeso/pavao"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4.0"
libc = "0.1.8"
log = "^0.4.14"
smbclient-sys = "^0.1.0"
thiserror = "^1.0.0"

[dev-dependencies]
argh = "0.1.7"
env_logger = "^0.9.0"
pretty_assertions = "^1.0.0"
rpassword = "5.0.1"
serial_test = "^0.6.0"

[features]
debug = []
with-containers = []

[[example]]
name = "transfer"
path = "examples/transfer.rs"

[[example]]
name = "tree"
path = "examples/tree.rs"
